// Please do not edit this file.

package main

import (
	"log"
)

type State int

const (
	On State = iota
	Off
)

type Eod int

const (
	Entry Eod = iota
	Do
	Exit
)

var eod Eod
var current State

func task() {
	switch current {
	case On:
		if eod == Entry {
			onEntry()
			eod = Do
		}
		if eod == Do {
			onDo()
			if pushButtonCond() {
				current = Off
				log.Println("State is changed: On to Off")
				eod = Entry
			}
		}
		if eod == Exit {
			onExit()
			eod = Entry
		}
	case Off:
		if eod == Entry {
			offEntry()
			eod = Do
		}
		if eod == Do {
			offDo()
			if pushButtonCond() {
				current = On
				log.Println("State is changed: Off to On")
				eod = Entry
			}
		}
		if eod == Exit {
			offExit()
			eod = Entry
		}
	}
}

func init() {
	current = On
	eod = Entry
}
