package mxgraph

import (
	"fmt"
	"io"
)

/*
【実装したもの】
・基本的なステートマシン図の変換を実装　〇
	→　 ・ステートマシン図の挙動をGo言語でどのように記述するか（sample.go, sample_edit.go）　〇
		・sampleを基に，ソースコードを出力する処理を記述　〇
・diagrams.netを用いて生成したXMLファイルから情報を取り出す　〇
・ステートマシン図から生成されたxmlファイルを基にソースコードを生成　〇
・二重構造のxmlファイルから情報を取り出す　〇

【すること】
・直接ファイルに出力する △
・合成状態の変換を実装
	→　 ・ステートマシン図の挙動をGo言語でどのように記述するか（sample.go, sample_edit.go）
		・sampleを基に，ソースコードを出力する処理を記述
*/

func remove(transition_list []*Transition, state_name *State) []*Transition {
	ret := make([]*Transition, len(transition_list))
	i := 0

	for _, transition := range transition_list {
		if state_name != transition.Src {
			ret[i] = transition
			i++
		}
	}

	return ret[:i]
}

// ------------------------------　output.go　-----------------------------------

func write_package(f io.Writer) {
	fmt.Fprintln(f, "// Please do not edit this file.")
	fmt.Fprintln(f, "// go run *.go")
	fmt.Fprintln(f, "")

	fmt.Fprintln(f, "package main")
	fmt.Fprintln(f, "")

	fmt.Fprintln(f, "import (")
	fmt.Fprintln(f, "\"fmt\"")
	fmt.Fprintln(f, ")")
	fmt.Fprintln(f, "")
}

func write_enum(f io.Writer, state_list []*State) {
	// enum宣言
	fmt.Fprintln(f, "type State int")
	fmt.Fprintln(f, "const (")
	for index, state := range state_list {
		if index == 0 {
			fmt.Fprintln(f, state.Name, "State = iota")
			continue
		}
		fmt.Fprintln(f, state.Name)
	}
	fmt.Fprintln(f, ")")
	fmt.Fprintln(f, "")

	fmt.Fprintln(f, "type Eod int")
	fmt.Fprintln(f, "const (")
	fmt.Fprintln(f, "Entry Eod = iota\nDo\nExit\n)")
	fmt.Fprintln(f, "")

	fmt.Fprintln(f, "var input string")
	fmt.Fprintln(f, "var eod Eod")
	fmt.Fprintln(f, "var current_state State")
	fmt.Fprintln(f, "")
}

func write_event(f io.Writer, transition_list []*Transition) {
	// 状態ごとの関数を作成
	fmt.Fprintln(f, "func task1() {")
	fmt.Fprintln(f, "switch current_state {")

	for _, transition := range transition_list {
		fmt.Fprintf(f, "case %s:\n", transition.Src.Name)
		state_name := transition.Src
		// Entry状態での動作を記述
		fmt.Fprintln(f, "if eod == Entry {")
		fmt.Fprintf(f, "%s_Entry()\n", transition.Src.Name)
		fmt.Fprintln(f, "eod = Do")
		fmt.Fprintln(f, "}") // if eod == Entry

		// Do状態での動作を記述
		fmt.Fprintln(f, "if eod == Do {")
		fmt.Fprintf(f, "%s_Do()\n", transition.Src.Name)
		// 遷移条件を列挙
		for _, transition := range transition_list {
			if state_name == transition.Src {
				fmt.Fprintf(f, "if %s_Cond() {\n", transition.Event.Name)
				fmt.Fprintf(f, "current_state = %s\n", transition.Dest.Name)
				fmt.Fprintf(f, "fmt.Println(\"State is changed: %s to %s\")\n", transition.Src.Name, transition.Dest.Name)
				fmt.Fprintln(f, "eod = Entry")
				fmt.Fprintln(f, "}") // if event_Cond()
			}
		}

		transition_list = remove(transition_list, state_name) // 表示したtransitionをリストから削除
		if len(transition_list) == 0 {
			break
		}
		fmt.Fprintln(f, "}") // if eod == Do
	}
	fmt.Fprintln(f, "}") // switch state
	fmt.Fprintln(f, "}") // func
	fmt.Fprintln(f, "}") // func
	fmt.Fprintln(f, "")
}

func write_init(f io.Writer, initial *State) {
	fmt.Fprintln(f, "func init() {")
	fmt.Fprintf(f, "current_state = %s\n", initial.Name)
	fmt.Fprintln(f, "eod = Entry")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")
}

// ------------------------------　output_edit.go　-----------------------------------

func write_package_edit(fe io.Writer) {
	fmt.Fprintln(fe, "// Please edit this file")
	fmt.Fprintln(fe, "// go run *.go")
	fmt.Fprintln(fe, "")

	fmt.Fprintln(fe, "package main")
	fmt.Fprintln(fe, "")

	fmt.Fprintln(fe, "import (")
	fmt.Fprintln(fe, "\"fmt\"")
	fmt.Fprintln(fe, "\"time\"")
	fmt.Fprintln(fe, ")")
	fmt.Fprintln(fe, "")
}

func write_func(fe io.Writer, state_list []*State, event_list []*Event) {
	for _, state := range state_list {
		fmt.Fprintf(fe, "func %s_Entry() {\n", state.Name)
		fmt.Fprintln(fe, "// nothing to do")
		fmt.Fprintln(fe, "}")
		fmt.Fprintln(fe, "")

		fmt.Fprintf(fe, "func %s_Do() {\n", state.Name)
		fmt.Fprintln(fe, "// nothing to do")
		fmt.Fprintln(fe, "}")
		fmt.Fprintln(fe, "")

		fmt.Fprintf(fe, "func %s_Exit() {\n", state.Name)
		fmt.Fprintln(fe, "// nothing to do")
		fmt.Fprintln(fe, "}")
		fmt.Fprintln(fe, "")
	}

	for _, event := range event_list {
		fmt.Fprintf(fe, "func %s_Cond() bool {\n", event.Name)
		fmt.Fprintf(fe, "// Please write the conditions under which a state transitions\n")
		fmt.Fprintln(fe, "return false")
		fmt.Fprintln(fe, "}")
		fmt.Fprintln(fe, "")
	}

}

func write_main(fe io.Writer) {
	fmt.Fprintln(fe, "func main() {")
	fmt.Fprintln(fe, "go func() {")
	fmt.Fprintln(fe, "for {")
	fmt.Fprintln(fe, "time.Sleep(1 * time.Millisecond)")
	fmt.Fprintln(fe, "task1()")
	fmt.Fprintln(fe, "}")
	fmt.Fprintln(fe, "}()")
	fmt.Fprintln(fe, "for {")
	fmt.Fprintln(fe, "fmt.Scan(&input)")
	fmt.Fprintln(fe, "if input == \"q\" {")
	fmt.Fprintln(fe, "fmt.Println(\"quit\")")
	fmt.Fprintln(fe, "break")
	fmt.Fprintln(fe, "}")
	fmt.Fprintln(fe, "}")
	fmt.Fprintln(fe, "}")
	fmt.Fprintln(fe, "")
}
