package modelTest

		// Please do not edit this file.

		import (
		// package name to import
		)

		const (
			debug = true
		)
		type TopState int
const (
On TopState = iota
Off
)


		type Eod int

		const (
			Entry Eod = iota
			Do
			Exit
		)
	var topeod Eod
var topCurrentState TopState

func TopStep() {
switch topCurrentState {
case On:
if topeod == Entry {
onEntry()
topeod = Do
}
if topeod == Do {
onDo()
if time3secCond() {
topCurrentState = Off
if debug {
logger.Println("State is changed: On to Off")
}
topeod = Exit
}
}
if topeod == Exit {
onExit()
topeod = Entry
}
case Off:
if topeod == Entry {
offEntry()
topeod = Do
}
if topeod == Do {
offDo()
if correctKeyCond() {
topCurrentState = On
if debug {
logger.Println("State is changed: Off to On")
}
topeod = Exit
}
}
if topeod == Exit {
offExit()
topeod = Entry
}
}
}

func init() {
topCurrentState = Off
topeod = Entry
}

