// Please do not edit this file.

package ledpkg

const (
	debugLog = true
)

type State int

const (
	On State = iota
	Off
)

type Eod int

const (
	Entry Eod = iota
	Do
	Exit
)

var eod Eod
var current State

func Task() {
	switch current {
	case On:
		if eod == Entry {
			onEntry()
			eod = Do
		}
		if eod == Do {
			onDo()
			if pushRightButtonCond() {
				current = Off
				if debugLog {
					debug.PrintLog("State is changed: On to Off")
					println("case:On print test")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			onExit()
			eod = Entry
		}
	case Off:
		if eod == Entry {
			offEntry()
			eod = Do
		}
		if eod == Do {
			offDo()
			if pushLeftButtonCond() {
				current = On
				if debugLog {
					debug.PrintLog("State is changed: Off to On")
					println("case:Off print test")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			offExit()
			eod = Entry
		}
	}
}

func init() {
	current = Off
	eod = Entry
}
