// base.go
// Please do not edit this file.

package model	

import (
	// package name to import
)

const (
	debug = true
)
	

// enum宣言
	type {{.TopWord}}State int

	// State名を羅列するように
	const (
		{{range .}}
			{{.StateName}}
		{{end}}
	)

	type {{.TopWord}}Eod int

	const (
		Entry {{.TopWord}}Eod = iota
		Do
		Exit
	)

	var {{.TopWord}}eod {{.TopWord}}Eod
	var {{.TopWord}}currentState {{.TopWord}}State


// task関数の生成
	// 状態ごとの関数を作成
	func Task() {
	switch current {
			{{range .}}
			case {{.StateName}}:

			// Entry状態での動作を記述
			if eod == Entry {
				{{.StateName}}Entry()
				eod = Do
			}

			// Do状態での動作を記述
			if eod == Do {
				{{.StateName}}Do()
			// 遷移条件を列挙
			{{range .}}
				if state_name == transition.Src {
					if {{.EventName}}Cond() {
						current = {{.TransName}}
						if debug {
							logger.Println("State is changed:" + {{.StateName}} + "to" + {{.TransName}})
						}
						eod = Exit
					} 
				}
			}
			{{end}}

			// Exit状態での動作を記述
			if eod == Exit {
				{{.StateName}}Exit()
				eod = Entry
			}
			{{end}}
		}
	}

// ステートの初期化

func init() {
	current = {{.InitialState}}
	eod = Entry
}
	