package kitchen

// Please do not edit this file.

// package name to import

const (
	debug = true
)

type OneState int

const (
	AlarmOn OneState = iota
	Countdown
	TimerSet
	NotSet
)

type Eod int

const (
	Entry Eod = iota
	Do
	Exit
)

var oneeod Eod
var oneCurrentState OneState

func OneStep() {
	switch oneCurrentState {
	case AlarmOn:
		if oneeod == Entry {
			alarmonEntry()
			oneeod = Do
		}
		if oneeod == Do {
			alarmonDo()
			if pushStartStopButtonCond() {
				oneCurrentState = NotSet
				if debug {
					logger.Println("State is changed: AlarmOn to NotSet")
				}
				oneeod = Exit
			}
		}
		if oneeod == Exit {
			alarmonExit()
			oneeod = Entry
		}
	case Countdown:
		if oneeod == Entry {
			countdownEntry()
			oneeod = Do
		}
		if oneeod == Do {
			countdownDo()
			if countdownEndCond() {
				oneCurrentState = AlarmOn
				if debug {
					logger.Println("State is changed: Countdown to AlarmOn")
				}
				oneeod = Exit
			}
			if pushStartStopButtonCond() {
				oneCurrentState = TimerSet
				if debug {
					logger.Println("State is changed: Countdown to TimerSet")
				}
				oneeod = Exit
			}
		}
		if oneeod == Exit {
			countdownExit()
			oneeod = Entry
		}
	case TimerSet:
		if oneeod == Entry {
			timersetEntry()
			oneeod = Do
		}
		if oneeod == Do {
			timersetDo()
			if pushStartStopButtonCond() {
				oneCurrentState = Countdown
				if debug {
					logger.Println("State is changed: TimerSet to Countdown")
				}
				oneeod = Exit
			}
		}
		if oneeod == Exit {
			timersetExit()
			oneeod = Entry
		}
	case NotSet:
		if oneeod == Entry {
			notsetEntry()
			oneeod = Do
		}
		if oneeod == Do {
			notsetDo()
			if pushTimerButtonCond() {
				oneCurrentState = TimerSet
				if debug {
					logger.Println("State is changed: NotSet to TimerSet")
				}
				oneeod = Exit
			}
		}
		if oneeod == Exit {
			notsetExit()
			oneeod = Entry
		}
	}
}

func init() {
	oneCurrentState = NotSet
	oneeod = Entry
}
