// Please do not edit this file.

package pkg

const (
	debug = true
)

type State int

const (
	On State = iota
	OffEmpty
	OffEntered
)

type Eod int

const (
	Entry Eod = iota
	Do
	Exit
)

var eod Eod
var current State

func Task() {
	switch current {
	case On:
		if eod == Entry {
			onEntry()
			eod = Do
		}
		if eod == Do {
			onDo()
			if time3secCond() {
				current = OffEmpty
				if debug {
					logger.Println("State is changed: On to Off")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			onExit()
			eod = Entry
		}
	case OffEmpty:
		if eod == Entry {
			offEmptyEntry()
			eod = Do
		}
		if eod == Do {
			offEmptyDo()
			if keyEnteredCond() {
				current = OffEntered
				if debug {
					logger.Println("State is changed: OffEmpty to OffEntered")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			offEmptyExit()
			eod = Entry
		}
	case OffEntered:
		if eod == Entry {
			offEnteredEntry()
			eod = Do
		}
		if eod == Do {
			offEnteredDo()
			if keyFailedCond() {
				current = OffEmpty
				if debug {
					logger.Println("State is changed: OffEntered to OffEmpty")
				}
				eod = Exit
			}
			if correctKeyCond() {
				current = On
				if debug {
					logger.Println("State is changed: OffEntered to On")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			offEnteredExit()
			eod = Entry
		}
	}
}

func init() {
	current = OffEmpty
	eod = Entry
}
