// Please do not edit this file.

package pkg

// package name to import

const (
	debug = true
)

type State int

const (
	Fasten State = iota
	UnFasten
	OnAlarm
)

type Eod int

const (
	Entry Eod = iota
	Do
	Exit
)

var eod Eod
var current State

func Task() {
	switch current {
	case UnFasten:
		if eod == Entry {
			unfastenEntry()
			eod = Do
		}
		if eod == Do {
			unfastenDo()
			if speedSensorOnCond() {
				current = OnAlarm
				if debug {
					logger.Println("State is changed: UnFasten to OnAlarm")
				}
				eod = Exit
			}
			if fastenSeatbeltCond() {
				current = Fasten
				if debug {
					logger.Println("State is changed: UnFasten to Fasten")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			unfastenExit()
			eod = Entry
		}
	case OnAlarm:
		if eod == Entry {
			onalarmEntry()
			eod = Do
		}
		if eod == Do {
			onalarmDo()
			if fastenSeatbeltCond() {
				current = Fasten
				if debug {
					logger.Println("State is changed: OnAlarm to Fasten")
				}
				eod = Exit
			}
			if speedSensorOffCond() {
				current = UnFasten
				if debug {
					logger.Println("State is changed: OnAlarm to UnFasten")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			onalarmExit()
			eod = Entry
		}
	case Fasten:
		if eod == Entry {
			fastenEntry()
			eod = Do
		}
		if eod == Do {
			fastenDo()
			if unfastenSeatbeltCond() {
				current = UnFasten
				if debug {
					logger.Println("State is changed: Fasten to UnFasten")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			fastenExit()
			eod = Entry
		}
	}
}

func init() {
	current = UnFasten
	eod = Entry
}
