// Please do not edit this file.

package keypad_complicate

// package name to import

const (
	debug = true
)

type State int

const (
	On State = iota
	Off
)

type Eod int

const (
	Entry Eod = iota
	Do
	Exit
)

var eod Eod
var current State

// パースした際の出力結果
// v.States &{On}
// v.States &{Off}
// v.Transitions {0xc00003eaf0 0xc00003eb30 0xc00003ec40}
// v.Initial &{Off}
// v.Events &{time3sec}
// v.States &{OffEntered}
// v.States &{OffEmpty}
// v.Transitions {0xc00003ebc0 0xc00003eb80 0xc00003ecb0}
// v.Transitions {0xc00003eb80 0xc00003ebc0 0xc00003ece0}
// v.Initial &{OffEmpty}
// v.Events &{keyFailed}
// v.Events &{keyEntered}
// PASS

// correctKeyイベントを取れていない（状態内にある状態から延びる矢印をとれていない．）

func Task() {
	// Off状態周りが出力できていない
	switch current {
	case On:
		if eod == Entry {
			onEntry()
			eod = Do
		}
		if eod == Do {
			onDo()
			if time3secCond() {
				current = Off
				if debug {
					logger.Println("State is changed: On to Off")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			onExit()
			eod = Entry
		}
	}
}

func init() {
	current = Off
	eod = Entry
}

// Please do not edit this file.

// package keypad_complicate

// import (
// // package name to import
// )

// const (
// debug = true
// )

// type State int
// const (
// OffEntered State = iota
// OffEmpty
// )

// type Eod int
// const (
// Entry Eod = iota
// Do
// Exit
// )

// var eod Eod
// var current State

// 領域ごとにパッケージの生成，ステート・変数の定義をしてしまう．

func Task() {
	// 状態内にある領域の状態名，初期状態，イベントはとれている
	// 全体の領域と，状態内の領域の差別化はできていない．

	switch current {
	case OffEmpty:
		if eod == Entry {
			offemptyEntry()
			eod = Do
		}
		if eod == Do {
			offemptyDo()
			if keyFailedCond() {
				current = OffEntered
				if debug {
					logger.Println("State is changed: OffEmpty to OffEntered")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			offemptyExit()
			eod = Entry
		}
	case OffEntered:
		if eod == Entry {
			offenteredEntry()
			eod = Do
		}
		if eod == Do {
			offenteredDo()
			if keyEnteredCond() {
				current = OffEmpty
				if debug {
					logger.Println("State is changed: OffEntered to OffEmpty")
				}
				eod = Exit
			}
		}
		if eod == Exit {
			offenteredExit()
			eod = Entry
		}
	}
}

func init() {
	current = OffEmpty
	eod = Entry
}
